<div class="gg-trans-wrap">
    <div id="google_translate_element">
        <div class="skiptranslate goog-te-gadget" dir="ltr" style>
            <div id=":0.targetLanguage" class="goog-te-gadget-simple" style="white-space: nowrap;">
            <img src="../img/cleardot.gif" class="goog-te-gadget-icon" style=" background-image: url(../img/te_ctrl3.gif); background-position: -65px 0px;">
            <span style="vertical-align: middle;">
            <a aria-haspopup="true" class="VIpgJd-ZVi9od-xl07Ob-lTBxed" href="#">
                <span>Chọn Ngôn ngữ</span>
                <img src="../img/cleardot.gif" alt width="1" height="1">
                <span style="border-left: 1px solid rgb(187, 187, 187);">&ZeroWidthSpace;</span>
                <img src="../img/cleardot.gif" alt width="1" height="1">
                <span aria-hidden="true" style="color: rgb(118, 118, 118);">▼</span>
        </a>
        </span>
        </div>
        </div>
        </div>