<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to enquiry list'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <!--<div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control qty_change" id="qty_change" data-bind="scope:'qty_change'">
                <!-- ko template: getTemplate() --><!-- /ko 
                <script type="text/x-magento-init">
                    {
                        "#qty_change": {
                           "Magento_Ui/js/core/app": {
                                "components" : {
                                    "qty_change": {
                                        "component": "Magento_Catalog/js/product/qty",
                                        "defaultQty": "<?php echo $block->getProductDefaultQty() * 1; ?>"
                                    }
                                }
                            }
                        }
                    }
                </script>
            </div>
        </div>
        <?php endif; ?>-->
        <div class="product-btn-wrap">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
			<a href="tel:(1)8663121652" class="call-us-btn">Call Us
			<img class="bao" src="<?= $block->getViewFileUrl('img/arrow-right-black.png'); ?>" alt="bao" />
			</a>
       
</div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>