<?php
<div class="suitabilities">
                            <div class="suitab-tooltip-wrap" style="line-height: 40px;display: inline-block;">
                    <img class="img-tooltip" style="margin-right: 10px;cursor: pointer;" data-title="Suitable for hot climates" src="/pub/media/images/product/suitability/hot-black.png">

                </div>
                                <div class="suitab-tooltip-wrap" style="line-height: 40px;display: inline-block;">
                    <img class="img-tooltip" style="margin-right: 10px;cursor: pointer;" data-title="Indoors" src="/pub/media/images/product/suitability/indoor-black.png">

                </div>
                                <div class="suitab-tooltip-wrap" style="line-height: 40px;display: inline-block;">
                    <img class="img-tooltip" style="margin-right: 10px;cursor: pointer;" data-title="Outdoors" src="/pub/media/images/product/suitability/outdoor-black.png">

                </div>
                                <div class="suitab-tooltip-wrap" style="line-height: 40px;display: inline-block;">
                    <img class="img-tooltip" style="margin-right: 10px;cursor: pointer;" data-title="Suitable for hazardous areas" src="/pub/media/images/product/suitability/haza-black.png">

                </div>
                                <span class="suitab-tooltip" style="display: none;">('Suitable for hazardous areas')</span>
                        </div>
?>