<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
 
<div data-block="minicart" class="minicart-wrapper"> 
    <a class="action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text-list"> Enquiry List<?= $block->escapeHtml(__('')) ?></span>
        <span class="dot3"
              data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() },
               blockLoader: isLoading">
            <span class="counter-number">(
                <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count')--><!-- /ko -->
                <!-- /ko -->
				)
            </span>
            <span class="counter-label">
             <!-- ko if: getCartParam('summary_count') -->
			 
                <!-- ko text: getCartParam('summary_count').toLocaleString(window.LOCALE) --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()):?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <p class="title">Enquiry List
                <span class="counter-number">(
                <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count').toLocaleString(window.LOCALE) --><!-- /ko -->
                <!-- /ko -->)
            </span>
			<button type="button" id="btn-minicart-close" class="action close" data-action="close" data-bind="
                attr: {
                    title: $t('Close')
                },
                click: closeMinicart()
            " title="Close">
<span data-bind="i18n: 'Close'">Close</span>
</button>
                </p>
                <!-- ko template: getTemplate() --><!-- /ko -->
                <div class=" action submit-enquiry">
                  <a style="display: block;width: 100%;"  href="<?php echo $this->getUrl('contact') ?>"><span>Submit enquiry list
				  </span>
				  <img src="<?= $block->getViewFileUrl('img/vector-right-white.png'); ?>" alt="" />
				  </a>
                   
					

                </div>
				 <div data-bind="html: getCartParamUnsanitizedHtml('extra_actions')"></div>
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else: ?>
        <?php $scriptString = <<<script
            require(['jquery'], function ($) {
                $('a.action.showcart').on('click', function() {
                    $(document.body).trigger('processStart');
                });
            });
script;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
    <?php endif ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], 'window.checkout = ' .
     /* @noEscape */ $block->getSerializedConfig(), false); ?>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
	
	
</div>

