<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Currency switcher
 *
 * @var \Magento\Directory\Block\Currency $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stores = $objectManager->create('Magento\Store\Api\StoreRepositoryInterface')->getList();
$conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue("web/unsecure/base_url");
?>

<?php if (count($block->getStores()) > 1): ?>
    <ul class="header-currency-list">

        <?php foreach ($stores as $store): ?>
            <?php if ($store->getCode() == 'admin') {
                continue;
            } ?>
            <?php $viewFileUrl = 'img/' . $store->getCode() . '.png'; ?>
            <li><a href="<?= $conf . $store->getCode(); ?>"><img src="<?= $this->getViewFileUrl($viewFileUrl); ?>"
                        title="<?= $store->getName(); ?>" /></a></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<div class="gg-trans-wrap">
    <div id="google_translate_element">
    <script type="text/javascript">
            function googleTranslateElementInit() {
                new google.translate.TranslateElement({ pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, autoDisplay: false }, 'google_translate_element');
            }
        </script>
        <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
            type="text/javascript"></script>
    </div>
	</div>


    

